services:
  db:
    build: ./backend/database
    container_name: postgres_ws_db
    restart: always
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: go_ws_backend
    restart: always
    ports:
      - "50505:5050"
    environment:
      - PORT=:5050
      - JWT_SECRET=secret
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./post-ui
    container_name: react_ws_frontend
    restart: always
    ports:
      - "40404:80"
    depends_on:
      - backend

volumes:
  postgres_data:
